all: true
include:
  - 'src/'
exclude:
  - '**/*.d.ts'
  - 'node_modules/'
  - 'webpack.config.js'
  - '**/webpack.config.js'
  - '**/.webpack/'
  - '**/coverage/lcov-report/*.js'
clean: true
temp-directory: 'coverage'
report-dir: 'coverage'
skip-full: true
reporter: [json, html, text]
check-coverage: false
